= Pagalnik
:doctype: book
:title: Pagalnik
:author: Jibran Halil Jibran
:toc: macro
:toc-title: Tabela de kontena
:title-logo-image: image:../.hev-wates/lidepla.svg[pdfwidth=1in]

[colophon]
[discrete]
== Pagalnik
Titla:: Pagalnik
Originale Titla:: The Madman
Autor:: Jibran Halil Jibran
Datum:: 1918
Tradukter:: Kristian Soto
Datum de tradukting:: Mes-char 2024
Lisensa:: "Pagalnik © 2024 bay Kristian Soto es lisensen bay CC BY-NC 4.0"

toc::[]

== Komo me he pagalifi

Yu kwesti me komo me he pagalifi. Eventi-te tak: Un dey, mucho bifoo ke Bohes
janmi-te, al jagifi fon chyen sonja, me dekovri ke may maskas bin choren, sem
maska ke me lepi-te e yusi-te duran sem jiva.

Me lopi wek tra ti fule de jenes na gatas krai-yen: “Chores!, Chores!, Damne
chores!”.

Manes e ginas ridi om me, e kelke jenes lopi a suy domes fobi-yen om me.

E wen me lai a basar-ney maidan, un boy stay-she on dom-ney ruf ek-krai: “Lu es
pagalnik!”

Me ek-lifti-te may vida fo vidi lu e surya kisi may nude fas pa un-ney ves. Pa
un-ney ves surya kisi may nude may fas e may atma en-infli de luba fo surya, e
me bu yao yo may maskas for. Kwasi in extas me ek-krai: “Blage, Blage bi chores
kel he chori may maskas”.

E tak es komo me he pagalifi.

E me he findi libritaa e anchuntaa in may pagalitaa; Libritaa om bi sole e
anchuntaa om bi samajen, bikos toy jenes kel samaji nu na fai gulan koysa de
nu.

Bat bye lasi me bi garwe om may anchuntaa, iven chor hi in prison es anchun de
otre-la.

== Boh

In dave taimes, wen un-ney lingwe sheikas lai a may labas, me go uupar sakrale
monta e me shwo a Boh, shwo-yen: «May lorda, me es yur gulam. Yur ahfe vola es
may jura e me obedi yu eternem.»

Bat Boh bu jawabi me, e go wek kwasi mahtaful storma.

E afte mil yar, me go uuparen sakrale monta e me snova shwo a Boh, shwo-yen:
«Kreater, me es yur kreatura. Fon glina yu he formi me e me debi a yu ol kwo me
es.»

E Boh bu jawabi me, e go wek kwasi milion de alas kway.

E afte mil yar me klimbi a sakrale monta e me shwo a Boh snova, shwo-yen:
«Patra, Me es yur son. Bay piti e luba yu fai janmi me, e bay may luba e puja me
heredi yur regilanda.»

E Boh bu jawabi me, e go wek kwasi veil kel kovri dale montas.

E afte mil yar, me klimbi a sakrale monta e snova me shwo a Boh, shwo-yen:
«May Boh, may gola e may fulfilsa; me es yur yeri e yu es may manya. Me es yur
riza in arda e yu es may flor in skay, kunem nu fa-gran bifoo fas de surya.»

Also, Boh inklini a me, e murmuri in may aures dolche wordas; e komo mar embrasi
rivakin, tak Boh embrasi me.

E wen me go nich a doles e planas, dar toshi ye Boh.

== May amiga

May amiga, me bu es kwo me sembli. May sembla bu es pyu kem klaida ke me porti,
klaida atemtem texen, kel protekti me om yur jigyas, e protekti yu om may
neglekta.

"Me" kel ye in me, may amiga, habiti in dom de silensa, e in it ve jivi sempre
bupersepte, buaksesibile.

Me bu wud mah yu kredi om kwo me shwo o mah yu fidi om kwo me zwo, bikos may
wordas es nixa pyu kem yur prope dumas transformen inu suon; e may aktas es yur
prope nadas transformen inu akta.

Wen yu shwo: «Feng fuki a esta», me shwo: «Ya, it fuki a esta»; bikos me bu wud
yao mah yu jan ke may menta bu mediti om feng, bat om mar.

Yu bu mog samaji may mar-ney dumas, ni me yao mah yu samaji to. Me wud preferi
bi solem kun mar.

Wen fo yu es pa dey, may amiga, fo me es pa nocha, yedoh, iven tak, me shwo om
middey kel dansi on kolinas e om yarkrude shadas kel ofnisi ahfem tra dol;
bikos yu bu mog audi ganas de may tumitaa ni vidi may alas bati kontra staras.
Me wud preferi bi solem kun nocha.

Wen yu go uupar a yur Swarga, me go nich a may Inferna. Iven dan, yu voki me tra
buatenibile abisma: «Kamarada, may kamarada», me jawabi yu: «Kamarada, may
kamarada», bikos me bu wud yao ke yu vidi may Inferna. Flama wud jal yur okos e
fum infli yur nos. E me gro-lubi may Inferna fo ke yu visiti it. Me wud preferi
bi solem in may Inferna.

Yu lubi veritaa, jamilitaa e justitaa; e me por yu shwo ke tu lubi las es hao e
byen. Bat in may kordia me ridi om tal luba. Bat me bu yao ke yu vidi may rida.
Me wud preferi ridi solem.

May amiga, yu es hao, chauke e atente; pyu iven, yu es perfekte, e me toshi
shwo yu sajem e chaukem. E yedoh, me es pagale. Bat me maski may pagalitaa. Me
preferi bi pagalnik sole.

May amiga, yu bu es may amiga, bat, Komo me mah yu samaji to? May dao bu es yur
dao; yedoh, nu promeni pa hunta, kun handas huntem.

== Faulafobika

Unves me shwo-te a faulafobika: «Yu mus bi fatige por pasi yur jiva in sey sole
agra.»

E ta jawabi-te me: «Plesir de fobising es koysa tanto glube e dure ke me bu
fatigi.»

Bifoo me reflexi-te idyen, me shwo-te ta: «To es vere, bikos me toshi koni-te
toy joisa.»

E ta jawabi-te me: «Sol toy wan kel es infuli bay slama na mog jan to.»

Also, me go-te wek sin jan ob ta fai-te laudi-worda a me oda ofensi-te me.

Pasi un yar duran ke faulafobika bikam-te filosofier.

E wen me pasi snova bli ta, me vidi dwa wuya kel zai-te bildi nesta sub suy
shapa.

== Somnipromeneres

In urba wo me jamni-te, habiti-te gina e elay docha. Ambi bi somnipromeneres.

Un nocha, duran silensa kuti munda, gina e docha promeni-yen somnem, miti-te in
ley tumanisen garden.

Mata shwo-te:

«Pa fin, pa fin, may dushman! Ela, por kel may jiva bin destrukten, Ela, kel
bildi-te suy jiva on ruinas de may-la. Magari me wud mog kili ela.»

Docha shwo-te:

«Oo, dushte gina, lao e egoiste, kel stay inter may libritaa e me! Kel wud yao
mah may jiva inu eho de suy jiva fade yo! Magari ela bi yo morte.»

Pa toy momenta kok gani, e ambi ginas jagifi.

Mata kwesti-te:

«Es yu hi, may kare».

E docha jawabi-te muy latif:

«Ya, mata.»

== Saje doga

Un dey unkwe, saje doga pasi-te bli kotatot.

Al he blisifi e vidi ke li bin muy distren e bu merki suy presensia, ta
stopi.

Pa toy momenta, gran e seriose kota lifti swa, vidi a otres e shwo:

«Prei ba, bratas; e wen yu he prei e riprei, e yu bu yo hev pyu dubas, also,
verem ve pluvi mauses.»

Al he audi toy wordas, doga ridi in suy kordia e go wek shwo-yen:

«Oo, blinde e pagale kotas! Ob bu es skriben e bu es jan-ney bay me e may
prajenes bifoo me, ke kwo pluvi bay forsa de preisas, fida e gro-pregi, bu es
mauses, bat ostas.»

== Dwa eremita

In sole monta jivi-te dwa eremita kel gro-pri Boh e lubi mutu.

Eremitas hev-te un kopa aus kicha, unike kosa ke li hev-te.

Un dey, dushte spiritu zin in kordia de zuy lao kem li kel shwo a zuy yunge:

«Nu jivi kunem, duran mucho taim. Es yo taim fo separi nu. Nu dividi ba nuy
hevsas.»

Also zuy yunge kem eremitas mah-triste e shwo-te:

«To afsosi me, brata, ke yu kwiti me. Bat si yu nidi go, tak ve bi.»

Lu bringi-te kiche kopa e dai-te, shwo-yen:

«Nu bu mog dividi it, may brata, kipi ba it.»

Also, zuy lao eremita desidem bakshwo-te:

«Me bu yao karitaa. Me bu pren kosa kel bu es may. Kopa mus bi dividen.»

E zuy yunge shwo-te:

«Si nu dividi kopa, ob fo ke it bi utile a yu o a me? Si yu konkordi, nu wud
mog jiti it.»

Bat zuy lao eremita snova shwo:

«Me bu yao to, bat justitaa e kwo es may, e me bu yao fidi justitaa e kwo es
may a kaprise shansa. Kopa mus bi dividen.»

Also, zuy yunge eremita bu mog toki pyu e shwo-te:

«Si es yur yaosa e to es kwo yu yao nu rupti kopa»

Fas de zuy lao eremita fa-tume pyu e pyu, e ta show-te:

«Damne fobnik, yu bu yao batali.»

== Tu dai e tu risivi

Unves jivi-te man kel hev dol fulfil de inglas. Un dey mata de Yeshu blisifi-te
ta e shwo ta:

«Amiga, may-son-ney klaida es toren e me nidi lati it bifoo lu ve go a mandir.
Ob yu mog dai ingla a me?»

Man dai-te a ela bu ingla, bat lernen bashan om tu dai e tu risivi, dabe ela
talimi it a Yeshu bifoo lu ve go a mandir.

== Sem ME

Duran ora zuy kalme pa nocha, wen me bin haf-somne, may sem Me sidifi pa sirkula
fo shwo bulautem.

Un-ney ME: «Hir, In sey pagalnik, me he jivi duran ol sey yares, sin zwo otre
koysa ke rinovisi suy tunga pa sabah e rikreati suy tristitaa pa nocha. Me bu
mog toleri pyu may destina e me ve rebelifi.»

Dwa-ney ME: «Yur fortuna es pyu hao kem may-la, brata, bikos me bin destinen fo
bi felise ME de sey pagalnik. Me ridi suy rida e gani suy felise oras, e bay
tri ala-ney pedas me dansi suy zuy lume dumas. Me hi es, kel mus rebelifi kontra
tanto fatige exista.»

Tri-ney ME: «Kwo me wud shwo, also, me es lube ME, me bin destinen fo kuydi
flami-she torcha de savaje pasion e fantastike tamanas. Es me hi, ti morbe por
luba na ME, kel rebelifi kontra sey pagalnik.»

Char-ney ME: «Inter oli yu, me es zuy tormenten, bikos nixa bin donen a me, bat
gro-hena e destruktive nopria. Me es, sturme ME, unike aus nu, kel janmi in
swate inferne guhas. Me hi es, kel wud protesti por servi a pagalnik.»

Pet-ney ME: «Non, Me hi es, dumishil ME, imajinishil ME, hunge e pyase ME, unike
kel bin kondamnen fo wandi sen reposi shuki-yen bukonen kosas e haishi bu
kreaten kosas. Me hi es, e bu yu, kel mus rebelifi.»

Sit-ney ME: «/ E me ku? Me es gunshil ME, pitishil gunjen, kel bay suy sabre
handas e tamane okos transformi deys inu pikturas e dai a deforme elementas nove
e eterne formas. Me hi es, sol-ney ME, kel mus rebelifi kontra sey notrankwile
pagalnik.»

Sem-ney ME: «Es strane ke yu oli yao rebelifi kontra sey jen por ke yu oli hev
desiden destina fo zwo. Aa, magari me bi kom yu e me toshi hev desiden destina!
Bat me bu hev nixa, me es, bugun-ney ME, kel sidifi silensem, vakue de Taim e
Spas, duran ke yu oli mangi rikreati-yen jiva. Dumi ba, es yu o me hi,
kamaradas, kel mus rebelifi?»

Wen sem-ney ME he shwo, otre-las kan shamem ta, bat nulwan shwo. E wen nocha
bikam pyu glube, un afte otre go somni kovri-nem in nove e santush subordina.

Bat sem-ney ME resti jage al kan nixa kel es avan ol kosas.

== Gwer

Un nokta, festa eventi-te in palas, man go-te e lagi-platifi swa avan prinsa.
Oli festeres vidi ta e vidi ke ta zai-te sangi e ke manki-te un oko. Prinsa
kwesti-te ta:

«Kwo eventi-te yu?»

E man jawabi-te:

«Oo, prinsa, me es anubav-ney chorer, e sey nocha, wen me vidi-te ke luna yok,
me go chori mani-shanjer-shop.

Wen me zin tra winda, me galti-te e me zin a texer-ney gunguan. Tumem me
trefi-te texitul kel austori may oko. E nau, oo, prinsa, me lai hir fo pregi
justitaa kontra texer.»

Also, prinsa komandi-te bringi texer, e wen ta ye avanem, prinsa ordoni-te ke
oni austori un de suy okos.

«Oo, prinsa» Texer shwo-te «Yur komanda es juste. Es hao ke yu komandi-te
austori un de may okos, bat pa afsos, may dwa okos es nesese dabe me mog vidi
texas kel me texi. Me hev visin kel es shu-kreater na e ta toshi hev dwa okos,
ta bu nidi suy dwa okos fo gun.»

Also, prinsa komandi-te bringi shu-kreater. E wen ta ye avanem, oni austori un
oko a ta.

E tak justitaa he zwo.

== Foxa

Foxa vidi-te suy shada pa suryachu, e show-te:

«Sedey me nidi ol kamel fo deyfan.»

E ta pasi-te ol sabah shuki-yen kameles. Bat pa middey ta vidi-te suy shada
snova, e shwo-te:

«Un maus ve sufi.»

== Saje rega

Unves, rega saje e potente regi in dale urba de Wirani, e lu bin foben por suy
potensia e luben pro su sajitaa.

In kordia de urba ye kwan, kel-ney akwa es freshe e kristal-ney. Fon it oli
sitisen pi e toshi iven rega e suy kortayuanes, bikos en Wirani bu existi
otre kwan.

Un nocha, duran oli zai somni, jadugina zin in urba e liti sem gutas de strane
likwa in kwan.

«Fon nau, hu pi sey akwa ve bikam pagale.» Jadugina shwo-te.

Pa sekwe sabah, oli, exepte rega e suy gran shambelan, he pi akwa fon kwan e
bikam pagale, tak kom jadugina preshwo.

E duran toy dey, oli sol murmuri mutu in tange gatas e in publike maidanes:

«Rega es pagale. Nuy rega e suy shambelan lusi ley rasum. Naturalem, nu bu mog
gei regi bay pagale rega. Treba detronvati lu.»

Toy nocha, rega komandi ke suy golde kopa bi fulen kun kwan-ney akwa. Oni bringi
it a lu, lu pi-te gro e dai-te toshi toy akwa a suy gran shambelan.

E eventi-te gran joysa in toy dale urba de Wirani, bikos rega e suy gran
shambelan rifindi ley rasum.

== Ambision

Tri man miti bli tabla de taverna. Un-ney man es texer, dwa-ney-la karpenter e
tri-ney-la pluger.

Texer shwo-te:

«Sedey me he vendi un delikate mortakapra de lin pur dwa pes golda. Nu pi ba ol
vino ke nu yao.»

«E me» Karpenter shwo-te «Me he vendi may zuy hao tabut. Nu chi ba gran rostiwat
kun toy vino»

«Me sol he kavi kabra» Pluger shwo-te «Bat por sey gunsa may shefa pagi-te
dwaplem a me. Nu yoshi chi ba madu-ney kekes.»

E pa ol toy nocha, taverna bin joysaful, bikos konstantem oni pregi vino, masu e
madu-ney kekes. E li bin muy joy-ney.

Taverna-masta froti-te suy handas e ridi-te a suy molya, bikos suy gastas spendi
sin limita.

Wen manes chu fon taverna, luna brili-te jamilem in skay e li promeni-te
gani-shem e krai-shem along gatas.

Hosta e suy molya stay in dwar de taverna e vidi li go wek.

«Aa» Molya shwo-te pa fin «Toy manes! Tanto donishil e joysaful! Si sempre nuy
fortuna bi tak, nuy son bu wud nidi bi taverner e gun mucho. Nu wud mog eduki ta
fo bi preiyan.»

== Nove plesir

Pa bifoo-nocha me inventi nove plesir, e wen me zai anubavi it pa un-ney ves,
anjel e demon arivi-te a may dom.

Li miti pa may dwar e en-diskusi om may yus inventen plesir.

Un-ney ek-krai:

«It es shmah!»

E otre-la protesti:

«It es dasin!»

== Otre lingwa

Tri dey afte may janma, wen me bin in may silke lulikama, me zai-te kan
astonem nove munda sirkum me, dan may matra shwo-te kun mamiligina:

«Komo sta may son?»

E mamiligina jawabi-te:

«Ta sta hao, madam. Me mamili ta trives, e me neva vidi-te kindakin do suy
yash, bi tanto joisaful.»

Me ek-krai-te indignem:

«To bu es ver, matra! May kama es twerde, e milka ke me suki-te na gusti karwe
fo may muh, e fauha de elay mamilas es gro-chou fo may nosdunes, e me senti muy
beda.»

Bat may matra bu samaji-te me (e toshi mamiligina), bikos lingwa ke me zai-te
shwo na bin de munda fon me lai.

E in dwashi-un-ney dey, wen oni zai-te kristisi me, pop shwo-te may matra:

«Yu mus bi felise hi, bikos yur son janmi-te kristayen.»

Me shwo-te surprisem a pop:

«Also yur matra kel ye in swarga na mus bi muy nofelise, bikos yu bu janmi-te
kristayen.»

Bat pop toshi bu samaji-te may lingwa.

E afte sem luna he pasi, preshwoer vidi-te me e shwo-te may matra:

«Yur son ve bi stater e gran lider.»

Bat me ek-krai-te:

«To es false preshwosa, bikos me ve bi musiker hi e sol musiker.»

Bat obwol may yash, haishi li bu samaji may lingwa e may fobitaa bin gro.

Pasi-te yo trishi-tri yar, duran may matra, mamiligina, e pop he morti (shada de
boh kovri ba li), bat preshwoer haishi jivi.

Me miti ta yeri bli mandir-ney dwar e duran nu kunshwo, ta shwo-te me:

«Me sempre jan-te ke yu bi gran musiker. Iven in yur kinditaa me preshwo yur
futur.»

E me kredi ta, bikos nau me toshi fogeti toy lingwa de otre munda.

== Anar

Unves, me jivi-te in kordia de anar, e me audi-te semenas shwo-she:

«Dey unkwe me ve bi baum, e feng ve gani inter may branchas, e surya ve dansi on
may lifes. Me ve bi forte e jamile duran ol sesones.»

also otre-la shwo-te:

«Wen me bin tanto yunge kom yu, me toshi hev-te tal somnas, bat nau wen me
samaji valor de kosas, me merki ke may nadas bin vane.»

E tri-ney-la toshi shwo-te:

«Me vidi in nu nixa kel wadi tanto astonival futur.»

E char-ney-la shwo-te:

«Tanto noutile wud bi nuy jiva, si nu bu hev pyu hao futur.»

Pet-ney-la shwo-te:

«Way nu diskusi om kwo nu ve bi, si nu bu jan kwo nu es?»

E sit-ney-la shwo-te:

«Obwol nu bu jan kwo nu es nau, sempre nu zai bi kwo nu es.»

E sem-ney-la shwo-te:

«Me hev idea muy klare om komo ve bi ol, bat me bu pai expresi it pa wordas.»

E poy ot-ney-la, nin-ney-la, shi-ney-la e otre-las shwo-te pa same taim, also me
bu mog samaji nixa om kwo li zai-te shwo inter mucho vos.

Por to, toy same dey me go-te a kordia de aiva, wo semenas es shao e hampi
silense.

== Dwa kafsa

In may-patra-ney garden ye dwa kafsa.

In un-la jivi leon ke may-patra-ney gulames bringi fon sahra de Niniveh; in
otre-la jivi garavel kel bu gani.

Kada dey al suryachu, garavel saluti leon shwo-yen: «Hao sabah! brata plennik.»

== Tri furmi

Tri furmi miti on nos de man kel somni-te sub surya. Afte saluti mutu segun
abyas de tribu de kada furmi, li en-toki:

Un-ney furmi shwo-te:

«Toy kolinas e planas bi zuy sahralik kem me koni in may jiva. Me pasi-te ol day
zai shuki semena unkwe e me bu findi nixa.»

Dwa-ney-la shwo-te:

«Me toshi findi nixa, malgree me visiti-te kada feldakin e angulakin kel ye hir.
Me dumi ke hir es arda ke may jenmin voki mole e muve e wo nixa kresi.»

Also, tri-ney-la ek-lifti-te suy fas e shwo-te:

«May amigas, nu ye on nos de sobrefurmi, mahtaful e nofin-ney, kel-ney korpa es
tanto gran ke nu bu mog vidi it, e kel-ney shada es tanto vaste ke nu bu mog
trasi it, e kel-ney vos es tanto mahta ke nu bu mog slu it. E ta es olilok-ney.»

Wen tri-ney-la fini shwo, otre-las vidi mutu e en-ridi.

Dan, man en-muvi e sonmem ek-lifti suy handa, skrapi suy nos e krushisi toy tri
furmi.

== Kabrakaver

Unves, wen me zai dafni may morte MES, kabrakaver blisifi-te me e shwo me:

«De oli kel lai hir, yu es unike jen ke me lubi.»

«Yur wordas mah me gro-joi» Me shwo-te ta. «Bat, plis, shwo ba me, way yu lubi
me?»

«Bikos oli jenes lai hir plaki-she e go wek plaki-she, e yu es unike jen kel lai
hir ridi-she e go wek ridi-she.»

== On mandir-ney gradina

Yeri pa aksham, on mandir-ney gradina, me vidi-te gina sidisi inter dwa man. Un
de suy wanga fa-pale e otra-la fa-rude.

== Sante urba

Pa may yungitaa oni rakonti me ke ye urba wo oli jivi segun skribituras.

E me shwo-te: «Me shuki toy urba e blagitaa kel ye in it.» Urba bi muy dale e me
zwo-te gran saplaisas fo safara. E poy charshi dey me kan-te urba e
charshi-un-ney dey me zin in la.

Bat, dar, ol jenes hev un oko e un handa. Fa-astoni-yen, me shwo shwo-te a me
swa: «Ob fo jivi in sey urba treba hev sol un oko e un handa?»

Also, me vidi-te ke li toshi fa-astoni bikos me hev may dwa oko e may dwa handa.
Al merki ke li kunshwo mutu, me kwesti-te li:

«Sey urba es Sante Urba ku, wo oli jivi segun skribituras?»

E li jawabi-te:

«Ya, es hir.»

E me kwesti-te:

«Kwo eventi-te a yu oli? Wo ye yur desna okos e yur desna handas?»

Oli fa-astoni por may ignora e koywan shwo me:

«Lai ba e vidi ba.»

Li dukti-te me a mandir, in ochak de urba, e in mandir me vidi gran monton de
handas e okos, ol suhisi. E me kwesti:

«Kwel konkester fai sey kruelitaa a yu oli?»

Li en-murmuri mutu e zuy lao kem li blisifi-te a me e shwo-te:

«Nu selfa zwo to. Boh fai-te a nu konkesti baditaa kel ye in nu.»

E lu dukti-te me a gao altar, e ol urba sekwi nu. E lu diki-te me skribitura
ingraven sobre altar, e me lekti-te:

«Si yur desna oko fai gunah a yu, pluki ba it ausen e weklansi ba it; bikos es
pyu hao fo yu ke un de yur membas tabahifi kem ol korpa bi lansen a inferna. E
si yur desna handa fai gunah a yu, auskati ba it e weklansi ba it; bikos es pyu
hao fo yu ke un de yur membas tabahifi kem ol korpa bi lansen a inferna.»

Dan, samaji-yen, me turni a jenes e en-krai-te:

«Ob existi inter yu, man o gina, kel hev dwa oko e dwo handa?»

E li jawabi me shwo-yen:

«Non. Nulwan. Bu existi jen integre, exepte toy wan kel es muy yunge fo lekti
skribituras e samaji komandas.»

E wen nu go ausen mandir, me hasti-muvi ausen Sante urba, bikos me bu es tanto
yunge e mog lekti skribituras.

== Boh do haotaa e Boh do baditaa

Boh do haotaa e Boh do baditaa miti-te uuparen monta.

Boh do haotaa shwo-te:

«Hao dey, brata.»

Boh do baditaa bu jawabi.

E Boh do haotaa, adi-te:

«Yu sta pa bade muda sedey.»

«Ya.» Shwo-te Boh do baditaa «Bikos laste taim, oni konfusi me kun yu mucho
veses, oni voki me bay yur nam e trati me komo si me bi yu, e me bu pri to.»

E Boh do haotaa shwo-te:

«E toshi oni konfusi me kun yu e oni voki me bay yur nam.»

Boh do baditaa go wek shatami-yen jen-ney stupiditaa.

== Hasima

Hasima, may hasima, may solitaa e may isola. Yu es fo me pyu kare kem milion de
triumfa, e pyu dolche a may kordia kem munda-ney gloria.

Hasima, may hasima, may me-selfa-ney jansa e may chunauta. Por yu me jan ke me
haishi es yunge e do ajile pedas, e bichivalful de lauras kel suhisi. E in yu me
findi solitaa e joysa om bi ignoren e bichen.

Hasima, may hasima, may zian e may shilda. In yur okos me he lekti ke bi
tronvaten es kom bi gulamen. E bi samajen es kom bi ponen nich. E bi konsaful bu
signifi pyu kem ateni fulitaa e kom mature fruta, lwo e bi konsumen.

Hasima, may hasima, may sempre brave kompanion, yu ve audi may ganas, may
skwilas e may silensas e nulwan exepte yu ve shwo me om ala-ney bating, e om
mar-ney agitas, e om motas kel jal pa nocha, e sol yu klimbi rokas e krutikas de
may atma.

Hasima, may hasima, valor kel neva morti. Yu e me ridi kunem in storma e kunem
nu kavi kabra fo olo kel morti in nu, e nu resti stan pa surya kun nobridibile
yaosa e nu ve bi danje.

== Nocha e Me

«Me es kom yu, oo Nocha: tume e nude. Me promeni tra flami-she dao kel es sobre
may drimas, e kada ves ke may peda tachi arda, dar gigante-gro baum kresi.»

«Non, yu bu es kom me, oo Pagalnik, bikos yu haishi kan bak fo meji pedatrasa
ke yu lyu-te in ramla.»

«Me es kom yu, oo Nocha: silense e glube. E in kordia de may solitaa ye Bohina
janmi-she son e in ta swarga e inferna tachi mutu.»

«Non, yu bu es kom me, oo Pagalnik, bikos yu haishi tremi bifoo tunga, e gana
de abisma fobisi-gro yu.»

«Me es kom yu, oo Nocha: savaje e terible; bikos may aures es fule de skwilas de
konkesten nasiones e sospiras de fogeten landas.»

«Non, yu bu es kom me, oo Pagalnik, bikos yu haishi hev yur syao Me kom
kamarada e yu bu mog bi amiga de yur gro-gran Me.»

«Me es kom yu, oo Nocha: kruele e dashat-ney; bikos may sina es yarke por
flami-she shipes, e may labas es mokre bay hema de kilen gwerjenes.»

«Non, yu bu es kom me, oo Pagalnik, bikos yu haishi aspiri yur twin-ney atma, e
yu bu bi sole kanun fo yu selfa.»

«Me es kom yu, oo Nocha: yunge e joisaful; bikos lu kel somni sub may shada na
bi pyan bay virge vino e ela kel sekwi me na shmahvati joisem.»

«Non, yu bu es kom me, oo Pagalnik, bikos yur atma es kuten in vual do sem
pliga, e yu bu teni yur kordia in yur handa.»

«Me es kom yu, oo Nocha: sabra-ney e pasion-ney; bikos in may sina, mil morte
luber es sinken in mortakapra do suhifen kisas.»

«Ob yu es, Pagalnik, verem kom me? Yu es kom me ku? Ob yu mog raidi storma kwasi
yu bi kaval e domini bliza kom zian?»

«Me es kom yu, oo Nocha, kom yu, me es gao e mahtaful. E may tron es bilden on
monton de morte lwo-ney Bohes, e yoshi bifoo me deys pasi fo kisi borda de may
klaida, bat neva fo vidi may fas.»

«Ob yu es kom me, son de may zuy tume kordia? E ob yu dumi may noalif dumas e
shwo may kosmike lingwa?»

«Ya, nu es twines, oo Nocha, bikos yu reveli spas e me reveli may atma.»

== Fases

Me he vidi fas do mil myenes, e fas do sol un myen, kwasi it bi in lepa. Me he
vidi fas kel-ney glansa bu kovri suy interne kurupitaa, e fas kel-ney glansa
kovri suy magnifike jamilitaa. Me he vidi lao fas do buexpresive rugas, e glate
fas in kel ol kosas bi ingraven. Me koni fases bikos me vidi tra kapra ke may
prope okos texi, e me shuki realitaa ke ye subem.

== Zuy Gran Osean

May Atma e me go-te bani swa a gran mar. Al lai-te a playa, nu shuki ahfe e sole
lok. Promeni-yen nu vidi man sidi om grey stone. Ta depon peses solta fon suy
sak fo weklansi it an mar.

«Ta es pesimista.» Shwo-te may Atma «Nu departi ba sey lok. Nu bu mog bani swa
hir.»

E nu promeni for til ateni baya. Dar nu vidi-te man kel stan on blan stone. Ta
hev-te in suy handas sunduk kun jamile stones krusten in it, fon it ta depon
peses sukra an mar.

«Ta es optimista.» Shwo-te may Atma «Ta toshi bu mog kan nuy nude korpa.»

Nu go for avan. E in playa nu vidi-te man kel kolekti morten fishes e lubem
returni li an akwa.

«Nu bu mog bani swa bifoo ta.» Shwo-te may Atma «Ta es filantropista.»

E nu go for avan.

Nu lai a lok, wo nu vidi man rasmi-she suy shada in ramla. Gran ondas lai e
fa-wek rasma, bat ta ribegin suy rasma un e otre ves.

«Ta es mistiker.» Shwo-te may Atma «Nu lyu ba ta.»

E nu kontinu-te til baya-ki, wo nu vidi man kolekti-she skuma e depon it in
alabaste kopa.

«Ta es idealista.» Shwo-te may Atma «Zaruu ta bu darfi vidi nuy nude korpa.»

E promeni-yen, nu turan audi vos kel krai:

«Sey hi es mar! Sey hi es glube mar! Sey hi es vaste e mahtaful mar.»

E wen nu he lai dar, nu vidi man kel-ney bey bi versu mar na hev mar-shel in suy
aur fo audi it-ney murmura.

May Atma shwo-te:

«Nu kontinu ba for. Ta es realista kel turni suy bey an olo ke ta bu mog lerni,
e fa-sate bay fragmenta.»

E nu go for avan. Inter stones ye-te man kel-ney kapa bi sinken in ramla. E me
shwo a may Atma:

«Nu mog bani swa hir bikos ta bu mog vidi nu.»

«Non!» En-krai may Atma «Ta es zuy bade kem ol. Ta es purista.»

Also gran tristitaa kovri fas de may Atma e suy vos.

«Nu go wek ba fon hir.» May Atma shwo me «Bikos yok ahfi o sole lok unkwe wo nu
bani swa. Me bu yao ke sey feng desordinisi may golde har, ni me yao diki may
blan busta a sey feng, ni me yao darfi a sey luma deskovri may nuditaa sakrale.»

Also nu lyu toy mar fo shuki zuy gran Osean.

== Inkrosen

Me en-krai-te a manes:

«Me yao bi inkrosen!»

E li shwo:

«Way yur hena mus fali on nuy kapas?»

E me jawabi-te:

«Bay kwel otre manera yu ve gei glorisi exepte inkrosi-yen pagalnikes?»

Li samaji to e me bin inkrosen. E Inkrosa trankwilisi-te me.

E wen me pendi-te inter arda e skay, li lifti-te suy kapas fo vidi me, e li
fa-joisaful, bikos neva bifoo li he lifti suy kapas. Bat al vidi me, un de li
kwesti-te:

«Por kwo yu yao bi auskupen?»

E otre-la en-krai-te:

«Por kwel kausa yu kurbanifi?»

E tri-ney-la shwo-te:

«Ob yu dumi ke yu mog kupi munde gloria pur toy prais?»

Also char-ney-la shwo-te:

«Vidi ba komo ta smaili. Ob mog bi pardonen tal tunga?»

E me jawabi a oli:

«Remembi ba ke me sol smaili.

Me kurbanifi por nixa, me bu yao gloria, me bu nidi bi auskupen.

Me he pyasi e me pregi a yu: "Dai ba me may hena fo pi it." Bikos kwo otre kosa
mog mah-wek pisa a pagalnik, exepte suy prope hena?

Me bin mute e me pregi a yu: "Katiwundi ba me, dabe toy wundas ve bi muhes."

Me bin plenisen de yur deys e yur nochas e me shuki dwar fo pyu hao deys e pyu
hao nochas.

E nau me ve departi tak kom otre inkrosnikes he departi. E bye dumi ke nu
fatigen de inkrosas. Treba fai inkrosas bay pyu hao jenes, in pyu hao ardas e
pyu hao skays.»

== Astronomier

Pa mandir-ney shada, may amiga e me vidi-te ti sidi sole na blinda. May amiga
shwo-te:

«Vidi ba saje man de nuy landa.»

Me lyu may amiga e me blisifi a blinda, me saluti lu e nu shwo-shwo. Afte kelke
taim me kwesti lu:

«Pardoni ba may kwesta, bat, Fon wen yu es blinde?»

Lu jawabi-te:

«Fon may jamna.»

Me shwo-te:

«Den kwel dao yu sekwi-te fo ateni tal sajitaa?»

Lu jawabi-te me:

«Me es astronomier.» Lu pon suy handa on suy sina e shwo-te: «Me vidi ol toy
suryas, lunas e staras.»

== Hom-siniansa

Me sidi hir, inter may brata monta e may sista mar.

Nu tri bi un in solitaa, e luba kel unisi nu na es glube, forte e strane. Verem
it es pyu glube kem may-sista-ney glubitaa, e pyu forte kem may-brata-ney forta,
e pyu strane kem may-pagalitaa-ney stranitaa.

Seklas afte seklas he pasi fon ke un-ney pale suryachu permiti nu vidi mutu.

E obwol nu he vidi janma, developa e morta de mucho mundas, haishi nu es sagarme
e yunge.

Nu es sagarme e yunge; bat, nu bu hev kompanion e nulwan visiti nu; E obwol nu
jivi hampi embrasem, nu senti swa nokonsolem. Kwel konsola mog existi fo
kontenen yaosa e represen pasion? Fon wo ve lai flame boh fo warmisi
may-sista-ney kama? Kwel strom tushi may-brata-ney agni? E hu es gina kel ve
regi may kordia?

Pa noche silensa, al somni, may sista murmuri bujan-ney nam de flame boh, e may
brata dalem voki lenge e dale bohina. Bat a hu me mus voki in may somna?

Me sidi hir, inter may brata monta e may sista mar. Nu tri bi un in solitaa, e
luba kel unisi nu na es glube, forte e strane.

== Herbinka

Herbinka shwo-te baum-ney liflwosa pa oton:

«Kwanto shum yu zwo wen yu lwo! Yu fobisi may hime sonjas.»

Liflwosa shwo-te indignen:

«Yu hi kel janmi pa nicha e jivi pa nicha na es nomuhim e bu mog gani! Yu hi, bu
jivi pa uupar e bu mog rekoni gana-ney suon.»

Liflwosa ateni arda e en-somni. E wen vesna lai, ta jafigi snova fon suy sonja e
nau ta bi herbinka.

Wen oton lai-te, e ta bi kapten bay hime sonjas, al floti in aira, lifes en-lwo
on ta. E ta murmuri pa selfa:

«Oo, sey oton-ney lifes, Kwanto shum li zai zwo. Li fobisi may hime sonjas.»

== Oko

Pa un dey, oko shwo-te:

«Traen sey doles, me vidi monta kovren bay blu snega. To es jamile bu ver?»

Aur en-audi e poy slu ol atentem, e shwo-te:

«Bat, Wo es toy monta? Me bu audi it.»

Also, Handa shwo-te:

«Me trai vanem tachi it, e me vu findi monta unkwe.»

Nos shwo-te:

«Monta yok! Me bu mog fauhi it.»

Also, Oko turni a otre taraf, e oli en-diskusi-te om strane halusina de Oko, e
li shwo-te:

«Koysa unkwe ku eventi a Oko?»

== Dwa sajnik

In dave urba de Afkar jivi-te dwa sajnik. Kada wan heni otre-la e bichi
otre-la-ney sajitaa, bikos un-la negi exista de Bohes, e otre-la es krednik.

Pa un dey, toy dwa miti in basar e pa miden suy subnikes, li en-disputi om
exista o buexista de Bohes. Al he diskusi duran oras, li separi-te.

Pa toy nocha, nokrednik go-te a mandir e genui bifoo altar e prei-te a Bohes fo
ke li pardoni suy pasi-ney galtas.

Pa same ora, ti bohes-ney shafer na otre-la jalifi suy sakrale kitabas, bikos
nau lu embrasi ateisma.

== Wen may Tristitaa janmi-te

Wen janmi-te may Tristitaa, me kresisi it dulem e kuydi it lubem.

E may Tristitaa fa-gao-te kom ol jivikas: forte, jamile e fule de astone kaif.

E nu lubi mutu, may Tristitaa e me, e nu lubi munda sirkum nu, bikos Tristitaa
hev-te karim kordia, e may-la bin karim kun Tristitaa.

E wen nu shwo-shwo, may Tristitaa e me, nuy deys bin ala-ney e nuy nocha bin
kamar-ney bay drimas, bikos Tristitaa hev-te shwotalente lisan e may-la bin
shwotalente kun Tristitaa.

E wen nu gani kunem, may Tristitaa e me, nuy visines sidi in suy windas fo audi
nu, bikos nuy ganas bin tanto glube kom mar e nuy melodias bin fule de strane
memorias.

E wen nu promeni kunem, may Tristitaa e me, jenes vidi nu kun mule okos e
murmuri noexplike dolchitaa. E ye kelke jenes kel vidi nu kun bukovre enva,
bikos Tristitaa bi noble, e me bi garwe kun Tristitaa.

Bat Tristitaa morti-te, kom ol jivikas, e pa sole, me dedikisi a studing e
mediting.

E nau, wen me shwo, may wordas sembli grave fo may aures.

E wen me gani, may visines bu lai fo audi may ganas.

E wen me promeni, nulwan vidi me.

Sol in may sonjas me audi voses kel shwo-te pitem:

«Vidi ba, dar ye man kel-ney Tristitaa he morti.»

== E wen may Joisa janmi-te

Wen may Joisa janmi-te, me dukti it inbrachem uupare may dom fo krai:

«Lai ba hir, may visines, lai ba hir e vidi ba, bikos he janmi may Joisa! Lai ba
e vidi ba sey ti ridi subsuryem na alegre kosa.»

Bat nul visin lai-te fo vidi may Joisa, e may astona bin gran.

E pa ol dey duran sem dey, me proklami-te may Joisa fon uuparen may dom, e
nulwan audi-te. E may Joisa e me bin solem sin ke nulwan shuki nu o visiti nu.

May Joisa fa-pale e fa-tedi, bikos nul otre kordia unkwe, bat may-la, admiri-te
suy jamilitaa, e nul otre labas unkwe, bat may-la, kisi-te suy labas.

Poy may Joisa morti-te por solitaa.

E nau me sol remembi may morten Joisa wen me remembi may morten Tristitaa. Bat
rememba es oton-ney lif kel murmuri in aira pa momentakin e poy bu suon pyu.

== Perfekte munda

Boh de luse atmas, yu, kel bi lusen inter bohes na audi ba me.

Dolche fata kel watha nu, pagale spiritus, wande spiritus na audi ba me.

Ti zuy defekte na me jivi pa miden perfekte rasa.

Ti jen-ney kaosa, gro-badal de konfuse elementas na me movi inter fine mundas,
inter ti komplete jura e pure ordina na jentas kel-ney dumas bi exakte e kel-ney
drimas bi haohunten e haokonstaten.

Suy dasines, oo Boh, bi mejen, suy gunah bi grave, e iven nokontise kosas kel
eventi in suryachu-ney tumitaa na, kel bu es ni dasin ni gunah na bi konstaten e
katalogen.

Hir, deys e nochas gei dividi e determini suluka, e gei regi bay regulas do
gran exaktitaa:

Tu chi, tu pi, tu somni, tu kovri prope nuditaa, also, tu fa-tedi pa prave taim.

Tu gun, tu plei, tu gani, tu dansi, also, tu fa-lagi wen kloka marki ora.

Tu dumi pa sertene fenshan, tu senti pa sertene fenshan, also, tu budumi, tu
busenti wen sertene stara liftifi pa horisonta.

Tu chori a yur visin pa smaili, tu ofri donas pa zarif handa-muva, tu laudi pa
sin exes, tu blami pa chauka, tu destrukti atmas pa un worda, tu agnisi korpa pa
spira, also, tu lavi prope handas wen dey-ney gunsa he fini.

Tu lubi segun stablen ordina, tu jui segun stablen manera, tu puji bohes
godi-nem, tu disturbi demones artaful-nem, also, tu fogeti ol, kom si memoria bi
morte.

Tu fai fantasia pa motiva, tu fai kontempla pa kuyda, tu fai felisa karesem,
tu fai sufra noblem, also, vakuisi tasa, dabe it mog gei fule pa manya.

Ol sey koysas, oo Boh, fa-konsepti intentem, fa-janmi determinem, fa-nani
exaktem, gei guverni bay regulas, gei dirigi bay rasum, also, bi kilen e sinken
segun preskriben metoda. E iven ley kabras lagifi in jente atma, las bi marken e
konten.

To es perfekte munda, munda do konsumen mahantaa, munda do sobre-ney divas,
zuy mature fruta in Boh-ney garden, zuy gao duma de universa.

Bat, way me ye hir? oo Boh, me, grin semena de busate pasiones, pagale storma
kel bu go ni esten ni westen, wande-she fragmenta de jal-she planeta.

Way me es hir? oo Boh de luse atmas, yu kel es lusen inter bohes.
